default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: process_files
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: process_files_development

test:
  <<: *default
  database: process_files_test

production:
  <<: *default
  database: process_files_production
  username: process_files
  password:
