default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: process_files

development:
  <<: *default
  database: process_files_development
  url: <%= ENV.fetch('DATABASE_URL') { "postgres://postgres:postgres@localhost/template_development" } %>

test:
  <<: *default
  database: process_files_test

production:
  <<: *default
  database: process_files_production
  username: process_files
  password:
